name: 'kepler github action for set up cluster'
description: 'kepler github action for set up cluster'
inputs:
  runningBranch:  # id of input
    description: 'runningBranch for kepler CI'
    required: false
  ebpfprovider:
    description: 'ebpf provider for kepler CI'
    required: false
  cluster_provider:
    description: 'k8s cluster provider for kepler CI'
    required: false
  kernel_module_names:
    description: 'comma delimited kernel module names to install for kepler CI, e.g. rapl,intel_rapl_msr'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
