name: Pull request

on: # yamllint disable-line rule:truthy
  pull_request:
    banches:
      - main

jobs:
  yamllint:
    uses: ./.github/workflows/yamllint.yml
  test:
    uses: ./.github/workflows/test.yml
  edge:
    uses: ./.github/workflows/testEdge.yml
