name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    # - run: npm test

  # test action works running from the graph
  test_bcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        runningBranch: bcc
    - name: verify
      run: |
        ./verify.sh bcc

  # test action works running from the graph
  test_local_cluster:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_provider: [kind, microshift]
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        runningBranch: ${{matrix.cluster_provider}}
        local_dev_cluster_version: v0.0.1
        cluster_provider: ${{matrix.cluster_provider}}
    - name: verify
      run: |
        ./verify.sh cluster

  # test action works running from the graph
  test_local_cluster_with_prometheus_grafana:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_provider: [kind, microshift]
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        runningBranch: ${{matrix.cluster_provider}}
        cluster_provider: ${{matrix.cluster_provider}}
        bcc_version: 0.25.0
        kubectl_version: 1.27.2
        local_dev_cluster_version: v0.0.1
        kind_version: 0.20.0
        prometheus_enable: true
        prometheus_operator_version: v0.12.0
        grafana_enable: true
    - name: verify
      run: |
        ./verify.sh cluster

