name: "units-test"
on:
  workflow_call:

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    # - run: npm test

  # test action works running from the graph
  test_ebpf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ebpf_provider: [bcc, libbpf]
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        ebpfprovider: ${{matrix.ebpf_provider}}
    - name: verify
      run: |
        ./verify.sh ${{matrix.ebpf_provider}}

  # test action works running from the graph
  test_local_cluster:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_provider: [kind, microshift]
        ebpf_provider: [bcc, libbpf]
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        ebpfprovider: ${{matrix.ebpf_provider}}
        local_dev_cluster_version: v0.0.3
        cluster_provider: ${{matrix.cluster_provider}}
    - name: verify
      run: |
        ./verify.sh cluster

  # test action works running from the graph
  test_local_cluster_with_prometheus_grafana:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_provider: [kind, microshift]
        ebpf_provider: [bcc, libbpf]
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        ebpfprovider: ${{matrix.ebpf_provider}}
        cluster_provider: ${{matrix.cluster_provider}}
        bcc_version: 0.25.0
        local_dev_cluster_version: v0.0.3
        prometheus_enable: true
        prometheus_operator_version: v0.12.0
        grafana_enable: true
    - name: verify
      run: |
        ./verify.sh cluster

