name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test_bcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        runningBranch: bcc
    - name: verify
      run: |
        dpkg -l | grep bcc

  # test action works running from the graph
  test_kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        runningBranch: kind
    - name: verify
      run: |
        dpkg -l | grep bcc
        docker ps -a
        kind get kubeconfig --name=kind
        kubectl get pods

  # test action works running from the graph
  test_microshift:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        runningBranch: microshift